// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meizwwqwchyrulgqxtfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1laXp3d3F3Y2h5cnVsZ3F4dGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDA3MDgsImV4cCI6MjA3MzA3NjcwOH0.wNgWxu-rDMFFaNvKkIEsOzKh7Ec76Lx6SP4XfOuART4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});